title: Rongzhi Dong | 董容智
description: PhD in Computer Science

url: "https://RongzhiDong.github.io"
baseurl: ""

remote_theme: "mmistakes/minimal-mistakes"
plugins:
  - jekyll-include-cache
  
author:
  name: "Rongzhi Dong"
  avatar: "/images/profile.jpg"
  bio: "Ph.D in Computer Science"
  links:
    - label: "Email"
      icon: "fas fa-envelope"
      url: "mailto:rongzhid@email.sc.edu"

    - label: "Google Scholar"
      icon: "fas fa-graduation-cap"
      url: "https://scholar.google.com/citations?user=Duqx0poAAAAJ"

collections:
  pages:
    output: true
    permalink: /:path/
  posts:
    output: false

defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single

navigation:
  main:
    - title: "About"
      url: /#About
    - title: "Research"
      url: /#Research
    - title: "Publications"
      url: /#Publications
    - title: "Service"
      url: /#Service
    - title: "Experience"
      url: /#Experience
    - title: "Awards"

footer_scripts:
  - /assets/js/scrollspy.js
      url: /#Awards
