title: Rongzhi Dong | 董容智
description: PhD in Computer Science

url: "https://RongzhiDong.github.io"
baseurl: ""

remote_theme: "mmistakes/minimal-mistakes"
plugins:
  - jekyll-include-cache
  
author:
  name: "Rongzhi Dong"
  avatar: "/images/profile.jpg"
  bio: >
    Ph.D., Computer Science  
    University of South Carolina
  email: "rongzhid@email.sc.edu"
  googlescholar: "https://scholar.google.com/citations?user=Duqx0poAAAAJ&hl=en&oi=ao"

collections:
  pages:
    output: true
    permalink: /:path/

defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single

navigation:
  main:
    - title: "Home"
      url: /
    - title: "Research"
      url: /research/
    - title: "Publications"
      url: /publications/
